pipeline {
    agent any

    environment {
        APP_NAME = "express-app"
    }

    stages {
        stage('Clean Workspace') {
            steps {
                deleteDir() // Ensures no leftover files from previous builds
            }
        }

        stage('Checkout Code') {
            steps {
                checkout scm // Fetch the current repo
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Run Express App with PM2') {
            steps {
                dir('frontend') {
                    // Stop old process if any
                    sh 'pm2 delete ${APP_NAME} || true'

                    // Start the app using PM2
                    sh 'pm2 start app.js --name ${APP_NAME}'
                    sh 'pm2 save'
                }
            }
        }
    }
}