pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Express App with PM2') {
            steps {
                sh 'pm2 delete express-app || true'
                sh 'pm2 start app.js --name express-app'
                sh 'pm2 save'
            }
        }
    }
}