pipeline {
  agent any

  stages {
    stage('Checkout Code') {
      steps {
        dir('frontend') {
          git url: 'https://github.com/mj1610/python_node_app.git', branch: 'main'
        }
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('frontend') {
          sh 'npm install'
        }
      }
    }

    stage('Restart Express App') {
      steps {
        dir('frontend') {
          sh 'pm2 restart express-app || pm2 start app.js --name express-app'
        }
      }
    }
  }
}
