pipeline {
    agent any

    environment {
        VENV_DIR = "venv"
        MONGO_URI = credentials('mongo-uri')
    }

    stages {
        stage('Inject Environment Variables') {
            steps {
                dir('backend') {
                    writeFile file: '.env', text: "MONGO_URI=${MONGO_URI}"
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('backend') {
                    sh '''
                        python3 -m venv ${VENV_DIR}
                        ./venv/bin/pip install --upgrade pip
                        ./venv/bin/pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Flask App with PM2') {
            steps {
                dir('backend') {
                    sh '''
                        pm2 delete flask-app || true
                        ./venv/bin/python -m flask --app app run &
                        pm2 start ./venv/bin/python --name flask-app -- app.py
                        pm2 save
                    '''
                }
            }
        }
    }
}
